debug: false

server:
 port: 9999
 context-path: /

spring:
 application:
  name: pay-admin

 devtools:
  restart:
   enabled: true

 cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5s

 thymeleaf:
   cache: false

 data:
    jpa:
      repositories:
        enabled: true

 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/payadmin?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456
  
######Druid数据源配置######
#连接池配置,下面配置说明请参考Druid Github Wiki，配置_DruidDataSource参考配置
  druid:
   initial-size: 3
   max-active: 10
   min-idle: 1
   max-wait: 60000
   pool-prepared-statements: true
   max-pool-prepared-statement-per-connection-size: 10
#等价于上面的max-pool-prepared-statement-per-connection-size
   max-open-prepared-statements: 10
   validation-query: select 1
   validation-query-timeout: 30000
   test-on-borrow: true
   test-on-return: false
   test-while-idle: true
   time-between-eviction-runs-millis: 60000
   min-evictable-idle-time-millis: 30000
   max-evictable-idle-time-millis: 60000
#默认值stat，配置多个英文逗号分隔
   filter:
     slf4j:
       enabled: true
######Druid监控配置######
#下面配置说明请参考Druid Github Wiki，配置_配置WebStatFilter
   web-stat-filter:
#是否启用StatFilter默认值true
    enabled: true
    urlPattern: /*
    exclusions: /druid/*
    sessionStatMaxCount:
    sessionStatEnable:
    principalSessionName:
    principalCookieName:
    profileEnable:

#下面配置说明请参考Druid Github Wiki，配置_StatViewServlet配置
   stat-view-servlet:
#是否启用StatViewServlet默认值true
    enabled: true
    urlPattern: /druid/*
    resetEnable:
    loginUsername: druid
    loginPassword: druid
    allow:
    deny: 255.255.255.255
#下面配置说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置,如果spring.datasource.druid.aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class=true
#Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
   aop-patterns: false


logging:
 level:
  root: info
  com:
   sand: debug
  org:
   hibernate: debug
   springframework: warn
   apache:
    shiro: debug
  config: classpath:logback.xml
